# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liste < Formula
  desc "Portable CLI roadmap tracker for humans and AI agents"
  homepage "https://github.com/pufferhaus/liste"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.0/liste_1.1.0_darwin_amd64.tar.gz"
      sha256 "dcc1ea8843bc57bd8e939bf94e0e95747eaae93326ed1cfcc142b600300b2ec5"

      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.0/liste_1.1.0_darwin_arm64.tar.gz"
      sha256 "6e32104458f3fd9a8f9d8f5a206cf93e61dba12e98e2703c77320f3a2b2c63e1"

      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.0/liste_1.1.0_linux_amd64.tar.gz"
      sha256 "b0afee266d9cde63bff8c1b8ea3843a25e01628881c971ccd85470d63cd9982d"
      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.0/liste_1.1.0_linux_arm64.tar.gz"
      sha256 "eb386f3a20f56af08a2934bfad878d7dcdf5b486d83a4e291111db28abc74cfb"
      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  def caveats
    <<~EOS
      Install Claude Code skills for AI agents:
        liste skills install

      Then add to ~/.claude/CLAUDE.md:
        At the start of every session, invoke the liste:session-start skill.

      Docs: https://github.com/pufferhaus/liste
    EOS
  end

  test do
    system "#{bin}/liste", "version"
  end
end
