# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liste < Formula
  desc "Tasks in markdown — a CLI for humans and AI agents"
  homepage "https://github.com/pufferhaus/liste"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.2/liste_1.1.2_darwin_amd64.tar.gz"
      sha256 "5b7be6698b17556d67946fe9de3a17832720fb8bf8f27ef47f4631c3b572ce1d"

      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.2/liste_1.1.2_darwin_arm64.tar.gz"
      sha256 "5b215927e34bb1bb54e195bc390dbfa9a5e42291a24bac26c260f088917cedff"

      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.2/liste_1.1.2_linux_amd64.tar.gz"
      sha256 "0ae3ad9edc6a0fa83f8a92d581715de9681f7671a88eda3a4ce217656d8c6170"
      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.2/liste_1.1.2_linux_arm64.tar.gz"
      sha256 "fcdb9780ee763765e40d16e090f49f4c66fd8dac7ae546a1855aa105e8b4198b"
      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  def caveats
    <<~EOS
      Install Claude Code skills for AI agents:
        liste skills install

      Then add to ~/.claude/CLAUDE.md:
        At the start of every session, invoke the liste:session-start skill.

      Docs: https://github.com/pufferhaus/liste
    EOS
  end

  test do
    system "#{bin}/liste", "version"
  end
end
